# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre Producto', max_length=70, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion Producto', max_length=100, null=True, verbose_name='descripcion')),
                ('valor', models.IntegerField(help_text='Valor del Producto', verbose_name='valor')),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.IntegerField(help_text='Numero de Boleta', verbose_name='boleta')),
                ('bici', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Bicicleta', verbose_name='bicicleta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='cliente')),
            ],
        ),
    ]
